{% set name = "autoflake" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 79c27c11efba4c7f35ca9747cdc2da0f5862fb0e0813c168fd781c0c572b9b01

build:
  number: 0
  noarch: python
  entry_points:
    - autoflake = autoflake:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - pyflakes >=1.1.0
    - python >=2.7

test:
  commands:
    - autoflake --help

about:
  home: https://github.com/myint/autoflake
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Removes unused imports and unused variables

extra:
  recipe-maintainers:
    - pmgrafe
    - asford
