travis:
  secure:
    BINSTAR_TOKEN: A7+TXXxKD06MF/+nSTw54ogVT7winCS5CS/wzoDdCaaMR5aGVGI5II9d8xn4c3pV+Gq4rLh7NP7pqcppDN4XFrHgOsoj45iIe4sVzgMEp6Bt9L7S0z8mE/L2WqC+E188ElDmrb72dZgGpRJqhr//M58oLMm1zrh7Fk1GceE1E1yfVQwyvU0TU8clB8b3PGOsYIAe3pVYqyFA3JidhI9gvgghBj4RmDbZQXKmu9lF1vpdZscx2KPqlcluYAYXAykX++YUGG22yGSK7EDVvAb77PVoVM9EY6d9Eg0E3GXtYsJnxTmC1stduZA7Rt1wUmg8GalfSbuG2krZy9kCyRfH7zZFW3Lo8nk3Lp5JooQHwhUBHPVePneycbv51b02vgQKyYpcBCUfUxF8dLC7UADu9ql+jan8stAz5R9KnpiGwodQ6LbIP+8lZLhoU3Les3LQjLyEj+T3OJuXeV503TqJPimTM0g9HUBg1k3uROcIqPuIwJVvYBqFRkdiZetoevdGoBh2rj7UxJs5XFjm1OdwxVhJ9htTgfF3AdumDkec4lkVjB5Xa+BOhO66EpbLh19ekW5XW/HITz5ayY3cLMl7kSsqfpZGOqfA2hZ4hVpQVbcxjSZYkWdENe4MPlSQ3FKL/vxMtO8PlY3VuunwiX4oYLgoB6NYU7NNFK5aYNaHVs0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
